Feat/admin portal
varunnivas/newstreet-website-proj pull request #3
Opened 2024-03-12 11:12 UTC by Kushank-NST

Admin Page with different sections in the side bar

2024-03-14 10:12 UTC, varunnivas commented on src/pages/AdminPage/components/FormComponent.jsx
> +  const token = 'your_token_here'; // Replace with actual token
what is the token here ? Please correct this

2024-03-14 10:16 UTC, varunnivas commented on src/pages/AdminPage/components/Sidenav.jsx
> +import { logoutUser } from '/Users/kushank/Desktop/Admin/newstreet-website-proj/src/pages/LoginPage/redux/UserSlice';
Use correct import path

2024-03-14 10:18 UTC, varunnivas commented on src/pages/AdminPage/pages/News/components/FormComponent.jsx
> +  const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjAyOGI5NzM2ZWZkZGQ5NTZkNzVjNyIsInVzZXJuYW1lIjoibnN0X2FkbWluIiwiaWF0IjoxNzEwMjU4OTY4LCJleHAiOjE3MTAzNDUzNjh9.JNMFgbIP3oRsYdT4u5k3w7Pc
What is this hard coded token ?

2024-03-14 10:19 UTC, varunnivas commented on src/pages/AdminPage/pages/News/components/News.jsx
> +      const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjAyOGI5NzM2ZWZkZGQ5NTZkNzVjNyIsInVzZXJuYW1lIjoibnN0X2FkbWluIiwiaWF0IjoxNzEwMjQzMDk5LCJleHAiOjE3MTAzMjk0OTl9.LqI9kLTYhfSjHtlZsW8f
hard coded token again

2024-03-14 10:22 UTC, varunnivas requested changes
folder structure needs to be changed. Components can be made more reusable , eg. so many similar files called FormComponent.jsx which is unwanted . Also in all the places the token is hard coded . It has to be taken from the login api response. Please address all the other comments to in the individual files . CSS styling has to be made better . So many lines of code used again and again

2024-03-22 07:27 UTC, Vaishakhsk commented on src/component/Validation.jsx
> +      'Password must contain at least 8 characters, one uppercase letter, one lowercase letter, one number, and one special character.'
add pop up for this

2024-03-22 07:28 UTC, Vaishakhsk commented on src/pages/AdminPage/components/Navbar.jsx
> +import AppBar from '@mui/material/AppBar';
didnt see navbar on your code, remove if not using

2024-03-22 08:24 UTC, Vaishakhsk commented on src/pages/AdminPage/pages/ClientTestimonial/components/ClientTestimonial.jsx
> +// import FormComponent from './FormComponent';
remove if you dont need to use them

2024-03-22 08:25 UTC, Vaishakhsk commented on src/pages/AdminPage/pages/Contact.jsx
> +                <th style={{ border: '1px solid white', padding: '8px', textAlign: 'center' }}>Name</th>
wrap under single component and reuse instead of duplicating the code

2024-03-22 08:25 UTC, Vaishakhsk commented on src/pages/AdminPage/pages/Contact.jsx
> +                  <td style={{ border: '1px solid white', padding: '8px', textAlign: 'center' }}>{query.name}</td>
here also duplication is present

2024-03-22 08:27 UTC, Vaishakhsk commented on src/pages/AdminPage/pages/News/components/News.jsx
> +                <th style={{ border: '1px solid white', padding: '8px', textAlign: 'center' }}>Title</th>
Duplication

2024-03-22 08:29 UTC, Vaishakhsk commented on src/pages/AdminPage/pages/Partners/components/Partners.jsx
> +                <th style={{ border: '1px solid white', padding: '8px', textAlign: 'center' }}>Name</th>
duplication

2024-03-22 08:39 UTC, Vaishakhsk commented on src/pages/LoginPage/container/LoginPage.css
> +    display: flex;
Consider using CSS classes or styled-components for consistent styling

2024-03-22 09:09 UTC, Abhishek121250 commented
ok
________________________________
From: Vaishakhsk ***@***.***>
Sent: Friday, March 22, 2024 2:09 PM
To: varunnivas/newstreet-website-proj ***@***.***>
Cc: Abhishek T ***@***.***>; Review requested ***@***.***>
Subject: Re: [varunnivas/newstreet-website-proj] Feat/admin portal (PR #3)


@Vaishakhsk commented on this pull request.

________________________________

In src/pages/LoginPage/container/LoginPage.css<https://github.com/varunnivas/newstreet-website-proj/pull/3#discussion_r1535231784>:

> @@ -0,0 +1,16 @@
+.LoginPageContainer {
+    display: flex;


Consider using CSS classes or styled-components for consistent styling

—
Reply to this email directly, view it on GitHub<https://github.com/varunnivas/newstreet-website-proj/pull/3#pullrequestreview-1954235923>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BGYOHQ3ERY2275PM3HFZGKDYZPU5TAVCNFSM6AAAAABESAQUSWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNJUGIZTKOJSGM>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-03-22 10:29 UTC, Kushank-NST commented on src/component/Validation.jsx
> +      'Password must contain at least 8 characters, one uppercase letter, one lowercase letter, one number, and one special character.'
validation is taken care from backend

2024-03-25 12:10 UTC, Vaishakhsk approved these changes, later dismissed

2024-03-25 12:52 UTC, merged